# Generated by Django 3.2.14 on 2024-08-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcityobject',
            name='city_distance',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecn.distancetocity', verbose_name='расстояние до города'),
        ),
    ]
