# Generated by Django 3.2.14 on 2024-08-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0002_alter_outcityobject_city_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcityobject',
            name='int_city_distance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='расстояние до города в км'),
        ),
        migrations.AlterField(
            model_name='outcityobject',
            name='city_distance',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecn.distancetocity', verbose_name='расстояние до города'),
        ),
    ]
