# Generated by Django 3.2.12 on 2024-08-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0003_auto_20240810_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcityobject',
            name='int_city_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='расстояние до города в км'),
        ),
    ]
