# Generated by Django 3.2.14 on 2024-08-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0004_alter_outcityobject_int_city_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcityobject',
            name='city_distance',
        ),
        migrations.DeleteModel(
            name='DistanceToCity',
        ),
    ]
